### ISSUE TITLE
mounting vss rw

### ISSUE THREAD

**Issue by KleBoR** [mnrkbys/vss_carver#11]
Hi,

would it be possible to somehow add the option to mount the vss as rw to use ntfsfix for repairs?

a lot of my test vss are not mountable cause of some errors like "Error reading bootsector: Input/output error"

if i dd the vss into a new image - mount this one rw and use ntfsfix to repair the sectores,  it is mountable.

So i was wondering if there are options to do this directly without dd'ing the vss again (which results in massive time and space consuming if big images are used..)

Thank you very much

EDIT: im using your patched vshadowmount

**Comment by mnrkbys** [comment]
From a DFIR perspective, any operation that involves rewriting disk images is incorrect.

**Comment by KleBoR** [comment]
I know this isnt right drom dfir perspective and i just want to focus on the header data.

would there be anyother way to get around this error? 
im currenty on a test bench and vss carver got me around 200 1.5tb snapshots of which some are mountable and some not (ca. 40/60).
So it would be great to get some other thoughts about how to fix the issue to access the unmountable vss =)

 Thank you
