### ISSUE TITLE
Unsupported number of stores

### ISSUE THREAD

**Issue by eisback** [mnrkbys/vss_carver#14]
Hi, I have a RAW image from a Windows Server which was encrypted in 2019 and all VSS snapshots were deleted by ransomware called phobos. What I did so far:

1. vss_carver.py -t RAW -o 68719476736 -i d:\server_image.img -c d:\server_catalog -s d:\server_store ([vss_carver](https://user-images.githubusercontent.com/51539891/154030543-f704d262-2aa3-4d8c-a954-0051c1dcb171.jpg))
2. vss_catalog_manipulator.py list d:\server_catalog

Now I see 105 (0-104) entries ([vss_catalog_list](https://user-images.githubusercontent.com/51539891/154023474-74a3ffb4-0806-47ad-8814-b2409b38fdcb.jpg)) but each line has a date from last week, why that?

3. vshadowmount.exe -o 68719476736 -c d:\server_catalog -s d:\server_store d:\server_image.img x:

Now I receive error messages like "unsupported number of stores"! So I reduce the number of restore points to just one:

4. vss_catalog_manipulator.py remove d:\server_catalog 0-103
5. vshadowmount.exe -o 68719476736 -c d:\server_catalog_remove -s d:\server_store d:\server_image.img x:

Now I can see an entry (x:\VSS1) and I can mount it with FTK Imager (https://accessdata.com/product-download/ftk-imager-version-4-5)

But no matter which restore point i choose, I always see the same version after the encryption! My impression is, that only the image after the infection is loaded and the VSS catalog is ignored! What am I doing wrong? Thanks!

**Comment by mnrkbys** [comment]
You can modify the upper limit of snapshots. The default is 99.
https://github.com/mnrkbys/libvshadow-vss_carver/blob/vss_carver/vshadowtools/mount_file_entry.c#L675
Of course, you have to compile libvshadow after modification.

Incidentally, in the latest source code, the upper limit has been increased to 999.
https://github.com/libyal/libvshadow/commit/3d8edda8c9f738adb38325d514672cb309869ef4#diff-cd0fe877fa99803f69368ba17311968495f9e57ea0d925fb04a69c82b000640eR675

**Comment by eisback** [comment]
Thank you! Unfortunately I am not a programmer... can you also implement this change in your precompiled libyal libraries? I don`t know how to use the original libvshadow from Joachim Metz with your VSS Carver ... thank you very much!

**Comment by mnrkbys** [comment]
If I have time, I will do it.
