### ISSUE TITLE
confusion in usage

### ISSUE THREAD

**Issue by dinidininta** [mnrkbys/vss_carver#2]
Sorry for posting this as an issue since i cannot find personal email of the developer.
I am new in the whole system volume and shadow copies situation.
Where can I find the value to fill the -o, -i, -c, and -s parameter in my computer?

Thank you very much in advance.

**Comment by mnrkbys** [comment]
You can use sleuthkit's mmls command to check number for -o. Other options are just file name.
And, please learn about digital forensics.
This tool is for digital forensics investigators and incident response handlers.

**Comment by palaz1s** [comment]
Hello @dinidininta 

Hope you are well.

Were you able to figure this out? I'm in a similar situation.

Thank you!
