### ISSUE TITLE
vshadowmount Segmentation Fault

### ISSUE THREAD

**Issue by wetsand24** [mnrkbys/vss_carver#4]
I am getting segmentation fault when mounting the image with store and catalog on kali linux.

![capture1](https://user-images.githubusercontent.com/41596376/51777616-d37ac880-20cb-11e9-87a8-3273df7a1e60.jpg)

**Comment by wetsand24** [comment]
can someone please help ? Its very important to recover the shadowcopies.

**Comment by mnrkbys** [comment]
The deb packages don't support Kali Linux.
