### ISSUE TITLE
ValueError: cannot fit 'int' into an offset-sized integer

### ISSUE THREAD

**Issue by KS-cyber** [mnrkbys/vss_carver#7]
Hi, this carver sounds amazing, btw.  I'm having a snag in use, however.  
Getting the error, "ValueError: cannot fit 'int' into an offset-sized integer".  I've simply added in a couple of print statements to see what integer it was getting (Otherwise, I've made no changes, so the line numbers are plus 2 in the screenshot).  
You can see that in the screenshot, right before the Traceback line.  
Am I doing something wrong?  I've double checked my partition offset, looks to be correct (Starting Sector 1159168 * 512)

![image](https://user-images.githubusercontent.com/54114725/63038520-f366b380-be86-11e9-903f-8cd21c50b737.png)

Thanks for your time!

**Comment by mnrkbys** [comment]
There is too little information to judge.
But "next catalog offset" parameter may be broken. It means that the catalog data was broken in your disk image.
There is a catalog data in your disk image, so I think you don't have to use this tool.
