### ISSUE TITLE
Store file empty.

### ISSUE THREAD

**Issue by adsystems** [mnrkbys/vss_carver#9]
Hi. Nice work 

I have 2tb image. After succefully Carver. The catalog have about 40kbs but  store file was 0 kb. Is norma? . And so i got and error with shadow mount.
Says: invalid range offset value exeeds file size.

 Any thoughts?
Thanks.

**Comment by mnrkbys** [comment]
Have you try vss_catalog_manipulator.py command?

**Comment by mnrkbys** [comment]
No response, so I'll close this.
